{
    "SSS": ["Shylo132", "MerlinMan5", "Starb", "ThomasCui", "Arigilos", "PlainCucumber25", "Kuruma", "DollarAkshay", "Pankpanther", "U-238", "Winnduu", "Salieri", "ChuChuChu", "Diesel13", "Penzz"],
    "FAG": ["Baldinater", "Doc360", "luketheduke"],
    "TheAngels": ["Samdalf", "WhiteHalmos", "Somotaw", "Nevrdid", "bugeyemonsters", "Sander", "Namahanna", "Tsungen", "Evanito", "JetBalsa", "Tynian"],
    "Vikings": ["JOURLOY", "Kartinka"],
    "WTH": ["Daggrz", "Zigmal"],
    "AHC": ["Dfett", "Cz4r", "Layl", "DavidTriphon", "DirtyLittleCodeMonkey"],
    "sru": ["JustLink", "sinicon", "SPACEGAMER"],
    "TPDT": ["Niconiconi", "TUR"],
    "PINK": ["InfiniteJoe", "Cade", "Palle", "dragoonreas", "Kendalor"],
    "PoA": ["Fluke", "Liquid"],
    "TheFort": ["OneThree111", "Geofflee", "Modus"],
    "KIWI": ["Aivaria", "MechWipf"],
    "TNG": ["heggico", "Genovese", "QzarSTB"],
    "NWC": ["KodeyTheNeko", "Skyline969"],
    "nato": ["nnog", "Midnight_Creeper", "Nev0x", "_BoB_", "maxbit89", "Triscus", "sparr", "MartyMoo", "Amadox"],
    "G_P": ["cooperg2001", "CyberDragon"],
    "fsoc": ["mightyleguan", "VisibleDucts", "Augl", "complexQuanta", "Shadowwulf", "Jestersheepy", "LordPong"],
    "Hive": ["Lamus", "Dewey", "Vervust", "PervyPenguin", "Rajecz", "Violaman", "IFor", "QuickStrike", "gastraph", "Tirao", "Baldey", "Vultured", "CrazyPilot", "McGnomington", "rouhet", "Dragnar", "haaduken", "userwins", "Greenfox", "kraiik"],
    "dal": ["herbo4", "Disconnect", "mortalitas", "CarrotCake"],
    "ANEO": ["Lowrentul", "thodalf", "alltheroads", "Saevatis", "Sammako"],
    "OJBK": ["sourwafer", "giftpresent", "BrianRotel", "Ruonyy", "CanisMinor"],
    "PNA": ["SquishProxy", "StellarLight", "CrAzYDubC"],
    "Umm": ["DKETwitch", "Emorelleum", "Lanatir"],
    "KOT": ["HerrLehmann", "Yunala", "sl0p3r", "Distaey"],
    "CatCon": ["KittyTack", "Tessaryn", "vijoc", "XATEV"],
    "JSisJ": ["MA3DL", "KARI3S", "morbrolhc", "MarquisBs", "Svarog1", "TheJP"],
    "DM": ["Strongmint", "Kuja"],
    "TheFeds": ["RZR0", "Gata", "Wurmus", "Pettingson"],
    "C3E": ["forkmantis", "Logmadr"],
    "YP": ["xndo", "Lexxicon", "Regnare", "ncsupheo", "Lolzor", "Baj", "Zpike", "Laeros", "omnomwombat", "cazantyl", "Zolcsika", "xsinx", "Geir1983", "admon", "adammada", "Vlahn", "Plemenit", "Orlet", "Subodai", "weaves", "Zyzyzyryxy", "Parthon", "NobodysNightmare", "TuN9aN0", "poppahorse", "Issacar", "Xaq", "Kenji", "Yilmas", "Komir", "Publiccert", "wolffman122", "Solace", "mnuck", "W4rl0ck", "smitt33", "likeafox", "Tijnoz", "Reizul", "Totalschaden", "SimpleEnigma", "joethebarber", "DoctorPC", "Turves", "tron", "Alcardian", "Tantalas"],
    "CFG": ["bitmapper", "hatterz", "Isntprepared", "Wynd"],
    "UV": ["Gemm", "Taedh", "MiloszeS"],
    "lss": ["KaZoiden", "PhillipK", "CokeJunkie", "WASP103", "PiratenBraut"],
    "AYCE": ["Timendainum", "Kasami", "Eiskalt", "DKPlugins", "slowmotionghost", "Atanner", "FeTiD", "Yoner", "SBense"],
    "TW": ["Arivul", "Balthael", "Aethercyn", "BlueskyFR", "Chris1", "HerrKai", "Enudoran", "Armaos", "GitLike", "Harlem"],
    "-": ["Orca", "common", "appu226"],
    "TM": ["Zuler", "M1kep", "Ratstail91"],
    "Overlords": ["PostCrafter", "Rising", "efyx", "Troedfach", "Tyac", "Arcath", "Blaugaard", "deft-code", "herghost", "Smokeman", "BarryOSeven", "BrinkDaDrink", "GimmeCookies", "wages123", "KageJ", "Kamots", "redTie", "Phisec", "HailHydra", "Zenga", "kirk", "Donat", "Pav234", "KOR_Solidarity", "ballisto", "SpaceRedleg", "Conventia", "Shibdib", "Vipo", "Picoplankton", "Ceggindeggar", "Mitsuyoshi", "Telemac", "SirFrump", "Nyoom"],
    "thunderkittens": ["SteeleR", "taiga", "Reini", "bonzaiferroni", "Jeb", "Vervorris"],
    "TGA": ["Fiskmans", "CeilingPanda"],
    "\u03bb": ["BuffyNZ", "ckitching"],
    "lun": ["Dr_Flizzle", "Sphic", "TheSirLancelot"],
    "AlphaCentauri": ["TheHeavenDemon", "linuxfreak23"],
    "TMBa": ["severedx", "Tirix", "Estecka", "MarvinTMB", "tablekorner"],
    "GEI": ["Adamant", "Braykin08", "Shadowist", "broswendes", "transfear"],
    "uca": ["GMan", "EmptySet", "Icon", "Artritus", "Spyingwind", "aster26", "Nam", "Zim"],
    "ud": ["Raddafiskie", "Garland", "Revrick", "p0x", "FuddyDuddy", "ScottyC", "vrs", "kmc2012", "a2coder", "Nisou", "squisher", "bekvon", "zaspect", "Azfaloth", "Enrico", "pseudonormal", "Mordox", "kshepard", "Laturb", "TranceCake", "Hosmagix"],
    "SCFR": ["iKlem", "Hollish"],
    "BoC": ["Almaravarion", "olo"],
    "C3PO": ["Xephael", "norca", "XyzzyPrime", "ryagas", "uvp", "TTR"],
    "SSL": ["AndyP", "M127"],
    "culture": ["DarkTrooper7", "Silesia", "Zergling", "SamTheCat", "Bombedoblib", "Skorp", "stybbe", "dormando", "Bovius", "n00bish", "Heilos", "daboross", "AWRyder", "maka_RTH", "evilmaniac", "Prime", "basepi", "Hernanduer", "Waveofbabies", "ags131", "tedivm", "anisoptera", "tinnvec", "NhanHo", "cyberblast", "Esryok", "Dissi"],
    "RRA": ["C33", "zomeity", "Seasnap"],
    "UB": ["Drxx", "WanderingUrsa"],
    "40k28": ["Christoth", "hyperpuke152", "Rurik"],
    "VIP": ["dund", "Haxxeris", "Mwaahahahaha", "Unstable", "MonsieurLee", "ManVsRice", "Faff", "Tempest"],
    "TBA": ["Builder", "Dubulicious", "kotyara", "duckymirror"],
    "enclave": ["ferdelyszys", "Pevik"],
    "int_max": ["Leonyx", "DewJunkie", "apemanzilla", "Winter_Owl", "Meridion", "Rexalicious", "Lur", "theKraken", "Dangermouse", "Hiryus", "Kalohi", "Selesthiel", "utiuti", "ShadyKutz", "starwar15432", "RediJedi", "Rubra", "Lisp", "Eugene95", "ZenTetra", "Jedislight"],
    "CoPS": ["ART999", "shadow_bird", "TiffanyTrump", "Jibol", "ICED_COFFEE", "szumi", "ThyReaper", "Kotarou", "Aundine", "Jumpp", "ben2", "mute", "Xist", "Montblanc", "iceburg", "Fritee", "Xolym", "demawi", "DomNomNom", "drckongen", "TheCreepz", "o4kapuk", "Robalian"],
    "AIN": ["shiz", "Schabo", "ThePaer"],
    "C3N": ["K-C", "Mudla", "DasBrain", "Spedwards", "tynstar"],
    "SRO": ["Morphaana", "weekOff", "SemperRabbit", "NihilRex"],
    "LK": ["Vaejor", "LordHein"],
    "SUN": ["Tanjera", "Voronoi", "BlackLotus", "seancl", "Ashburnie", "Lomewilwarin", "ChaosDMG", "Calame", "DoofenShmirtz", "Baezon", "Hachima", "joshua00214", "roncli", "Xoc", "neomatrix", "Klapaucius", "Finndibaen", "Gink", "Nephanae", "bldinator", "Sheeo", "zGeneral", "andrwmorph", "Maxion", "Atlan", "Pundemonium", "deadlypineapple"],
    "Nico": ["gooseThief", "gitHappens"],
    "LEGS": ["Chobobobo", "SirLovi"],
    "CF": ["0mni", "Sanyu", "GOREACRAFT"],
    "UoP": ["RoyalKnight", "BBleae", "Cciradih", "Torara", "zzsstt644", "foreyes1001", "czc", "LoAT_Kyoma", "composite_x", "Lev_CT", "KevinH", "a02418", "Aurium", "wyt", "bestkurisu", "Noswir", "Stranger130126", "ayoitsLuke", "LisbethCeceri", "BestJohn", "Hibari", "ciwomuli", "Yuandiaodiaodiao", "ChenyangDu", "LokiSharp", "Lampese", "sjfhsjfh", "HoPGoldy", "masterkeze", "EricGuo", "BoosterKevin", "foraphe", "TPEZ", "fangxm", "Asixa", "WheatEars", "Unwannadie", "Cookies", "Christinayo"],
    "Unity": ["Eijolend", "FourPawsUnder", "TinyMan", "Brickshitter"],
    "EoD": ["Patrik", "iSPANKzombiez", "Neogost", "Ezghoul", "superxwolf"],
    "END": ["Zeus", "Sheph", "Moria", "rber", "ricane", "n0ne"],
    "DRAGON": ["Gin", "AMD", "Wagsn", "Lucky777777", "JanKing"],
    "COJ": ["Radonite", "Lithia", "siro", "Douggernort", "rysade"],
    "URC": ["LePlon", "Thinx"],
    "Theoran": ["Creepermillion5", "TheLongFellowPLAYER"],
    "URoC": ["Manuel341", "Cyb3r"]
}
